### ISSUE TITLE
Support synchronous network checks

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#1046] opened 2017-01-23 22:15 UTC
Either by allowing `web3.version.getNetwork()` with no callback, or by providing a property (which would be a superset of the web3 standard).

**Comment by kumavis** [comment] 2017-01-29 10:10
easy enough, we already have the plumbing in place for selected account

**Comment by Zanibas** [comment] 2017-02-16 19:38
Is this a duplicate of #1085?

**Comment by kumavis** [comment] 2017-02-16 19:40
yes

**Closed by kumavis** 2017-02-16 19:40 UTC
Labels: enhancement, ready
