### ISSUE TITLE
Metamask asks the password with each livereload in frontend

### ISSUE THREAD

**Issue by DavidBelinchon** [MetaMask/metamask-plugin#1124] opened 2017-02-16 14:20 UTC
Hello!
I'm using metamask in a frontend aplicacion, when I do changes in .html or .js they do a livereload in this point metamask lose the password and ask me again.
Just happens in livereload if I refresh the page works normally.
Also I'm tried to remove all web3 in my aplication and happens the same, for this reason I think is metamask issue.
I'm using this angular generator to try this:
https://github.com/yeoman/generator-angular 

thanks!! and Nice plugin!

**Comment by Zanibas** [comment] 2017-02-16 18:13
This is normal behavior--whenever the livereload detects a change, the application gets reloaded, which triggers the background pages to get refreshed. This consequently locks the page due to the logic in our code making the app locked by default at instantiation.

**Comment by flyswatter** [comment] 2017-02-16 18:22
This is a little different than that, @Zanibas.  He says changing *his* application reloads MetaMask.  I haven't heard of this.

You say you can reproduce this with the brand new generator, @DavidBelinchon?

**Comment by kumavis** [comment] 2017-02-16 18:27
Sounds like we are not disabling our dev livereload hooks in prod

**Comment by Zanibas** [comment] 2017-02-16 19:12
May be fixed by the discussion in #1126, which is "we'll make sure the next build actually disables livereload...not sure why it didn't last time."

We will close if this is the case by the next deployment!

**Comment by Zanibas** [comment] 2017-02-21 00:05
Seems to be fixed--please re-open if the issue wasn't resolved!

**Closed by Zanibas** 2017-02-21 00:05 UTC
Labels: fixed-in-dev, in progress

**Comment by DavidBelinchon** [comment] 2017-02-21 07:31
Thanks! I can try today! ^^

**Comment by DavidBelinchon** [comment] 2017-02-21 07:35
it works! thanks for all! :)
