### ISSUE TITLE
Error: PortDuplexStream on getNetwork

### ISSUE THREAD

**Issue by gkapkowski** [MetaMask/metamask-plugin#1334] opened 2017-04-23 08:58 UTC
Version: 3.5.2

Steps to reproduce:
1. Go to Metamask
2. unlock account
3. Change current network
4. Execute `web3.version.getNetwork((a,b) => {console.log(a, b);})` in console

The error underneath is:
```
message: "Cannot read property 'impl' of undefined"
stack: "TypeError: Cannot read property 'impl' of undefined
at getPrivateImpl (extensions::utils:130:30)
at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:148:20)
at PortDuplexStream._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:270:18)
at doWrite (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4997:64)
at writeOrBuffer (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4986:5)
at PortDuplexStream.Writable.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4924:11)
at PostMessageStream.ondata (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:4069:20)
at PostMessageStream.EventEmitter.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:2696:20)
at readableAddChunk (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:3740:18)
at PostMessageStream.Readable.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:3699:10)"
```

**Comment by flyswatter** [comment] 2017-04-23 21:05
This is a duplicate of #873.  Switching the network currently crashes our background process, and breaks the current app's connection to the web3 provider.

**Closed by flyswatter** 2017-04-23 21:05 UTC
Labels: bug
