### ISSUE TITLE
Incompatibility with browser-solidity

### ISSUE THREAD

**Issue by drcode** [MetaMask/metamask-plugin#880] opened 2016-11-23 01:54 UTC
1. Go to https://ethereum.github.io/browser-solidity with metamask-enabled chrome.
2. On the third tab, choose "injected web3"
3. Press the red "create" button on any contract
4. In the javascript console, note the error "Uncaught Error: invalid address"

(I duplicated this on 2 machines- But it could still just be a local machine issue or a browser-solidity issue.)

**Comment by jdetychey** [comment] 2016-11-23 10:34
I am also having the same incompatibility with browser solidity. Full js log:
`MetaMask - injected web3 app.js:15262`
`Loading https://ethereum.github.io/solc-bin/bin/soljson-v0.4.6+commit.2dabbdf0.js without worker
app.js:14458` 
`Uncaught Error: invalid address(…)` 

everything loads properly on other websites like https://fdi.etherisc.com/

**Comment by flyswatter** [comment] 2016-11-23 18:22
I reproduced your issue, thanks for the great steps, @drcode.

For some reason it seems that browser-solidity is no longer grabbing the current address as the sender when assembling the Contract-submission tx, and so what you're seeing is a browser-solidity error that it throws when it is asked to send a transaction that has an invalid sending address.

In the `Method.prototype.buildCall` function, you can see this line:
```
var payload = method.toPayload(Array.prototype.slice.call(arguments));
```

The input arguments are very minimal, and the resulting `payload` value lacks a defined sender:
```javascript
{from: undefined, to: undefined, data: "0x606060405234610000575b33600060006101000a8154817000816000905550600101610594565b5090565b50505b5056", value: "0x0", gas: 449552}
```

This makes it look like the `method.toPayload()` method is failing to pull out the current address from the injected `web3`.

Unfortunately, when I did [a search of their repository](https://github.com/ethereum/browser-solidity/search?utf8=%E2%9C%93&q=toPayload), I saw no `toPayload` reference anywhere, so now I'm confused.

This *seems to be* a browser-solidity bug to me right now, but without the original source code to search & reference, it will be hard for me to track down.

I've opened [an issue with browser-solidity here](https://github.com/ethereum/browser-solidity/issues/342).

**Comment by yann300** [comment] 2016-12-12 10:34
So the fix is pushed fixed, please could you confirm and close if everything fine.

**Comment by flyswatter** [comment] 2016-12-13 23:08
Looks right, thanks @yann300!

**Closed by flyswatter** 2016-12-13 23:08 UTC
Labels: blocked, bug
