### ISSUE TITLE
Dropbox site has errors / not functional with metamask enabled

### ISSUE THREAD

**Issue by illz** [MetaMask/metamask-plugin#1524] opened 2017-05-31 21:56 UTC
When MetaMask is enabled, dropbox's Files listing is broken. Disabling the extension fixes it.

I see this error in the console:
init_react-vflmdBdlQ.ts:74 
TypeError: o.getScope is not a function
    at y (browse_keyboard_shortcuts-vfleu4pB9.ts:140)
    at b (browse_keyboard_shortcuts-vfleu4pB9.ts:219)
    at Object._setupKeyboardShortcuts (item_list_legacy-vfltr5xHi.coffee:244)
    at Object.componentDidMount (item_list_legacy-vfltr5xHi.coffee:181)
    at e.notifyAll (react-dom-15.5.4-prod.min-vfleCs-fP.js:12)
    at r.close (react-dom-15.5.4-prod.min-vfleCs-fP.js:14)
    at r.closeAll (react-dom-15.5.4-prod.min-vfleCs-fP.js:15)
    at r.perform (react-dom-15.5.4-prod.min-vfleCs-fP.js:15)
    at s (react-dom-15.5.4-prod.min-vfleCs-fP.js:14)
    at r.perform (react-dom-15.5.4-prod.min-vfleCs-fP.js:15)

**Comment by flyswatter** [comment] 2017-05-31 22:01
We're actually aware of this issue, so closing this as a duplicate of #1321, we'll be tracking its progress there, hopefully we'll get to it soon.

**Closed by flyswatter** 2017-05-31 22:01 UTC
