### ISSUE TITLE
Store MetaMask-Config key for every sites

### ISSUE THREAD

**Issue by fonzarely** [MetaMask/metamask-plugin#907] opened 2016-12-02 15:37 UTC
I've found the MetaMask-Config key created for sites that does not have Dapp (google, lemonde.fr).
It might be possible to make the creation only when the web3 api is used and not only at module boot time (which is what I think it does).

Other than that Metamask is great !
Cheers,

**Comment by kumavis** [comment] 2016-12-02 16:07
we can easily remove that by removing support for `web3.eth.accounts`

**Comment by flyswatter** [comment] 2016-12-02 19:44
This is a duplicate of #537, we definitely intend to add per-domain sign-in eventually, largely for privacy concerns, but also performance benefits.

**Closed by flyswatter** 2016-12-02 19:44 UTC
