### ISSUE TITLE
Mystery crash when >4 extensions on Windows

### ISSUE THREAD

**Issue by flyswatter** [MetaMask/metamask-plugin#758] opened 2016-10-21 23:45 UTC
Reported by @kennyrowe 

His machine is:

```
OS Name    Microsoft Windows 7 Enterprise
Version    6.1.7601 Service Pack 1 Build 7601
Other OS Description     Not Available
OS Manufacturer    Microsoft Corporation
System Name    
System Manufacturer    Dell Inc.
System Model    Latitude E7470
System Type    x64-based PC
Processor    Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, 2501 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date    Dell Inc. 1.2.2, 1/19/2016
SMBIOS Version    2.8
Windows Directory    C:\Windows
System Directory    C:\Windows\system32
Boot Device    \Device\HarddiskVolume2
Locale    United States
Hardware Abstraction Layer    Version = "6.1.7601.17514"
User Name    
Time Zone    Pacific Daylight Time
Installed Physical Memory (RAM)    8.00 GB
Total Physical Memory    7.67 GB
Available Physical Memory    1.10 GB
Total Virtual Memory    28.6 GB
Available Virtual Memory    18.6 GB
Page File Space    20.9 GB
Page File    C:\pagefile.sys
```

**Comment by flyswatter** [comment] 2016-10-21 23:46
@Zanibas I'm assigning this to you since you got a new windows machine up and running, although I guess I could always do a VM.

Anyways, we'll try to reproduce early next week.

**Comment by kennyrowe** [comment] 2016-10-21 23:46
Crashes specifically when changing from testnet to live net. Crash resolves when the total number of chrome extensions enable is less than or equal to 4

**Comment by kennyrowe** [comment] 2016-10-21 23:47
Chrome Version 53.0.2785.143 m

**Comment by Zanibas** [comment] 2016-10-26 17:52
Currently seeing no issues on Windows 10, will try running a Windows 7 instance, but if we may ask, what are the extensions you're running alongside MetaMask?

**Comment by kennyrowe** [comment] 2016-10-26 20:03
@Zanibas many, but it doesn't seem to matter which only how many.

I'll PM you the list

**Comment by Zanibas** [comment] 2016-10-27 23:31
Ran MetaMask on a Windows 7 instance on chrome 54, with all extensions mentioned on the list. Not able to replicate any crashes yet.

Can you describe in more detail what the crash looks like? Also, it may be that Chrome 53 is causing these issues--are you able to upgrade to Chrome 54? Currently running on my VM is 54.0.2840.71 m. I've tried finding this chrome version to verify this, but at this point, this is what I'm leaning towards.

**Comment by kennyrowe** [comment] 2016-10-27 23:34
Version 54.0.2840.71 m I've looked around for a chrome crash report but no luck yet

**Comment by kennyrowe** [comment] 2016-10-27 23:37
p.s. the crash only happens when switching from Live net to Morden

**Comment by Zanibas** [comment] 2016-10-28 17:57
If you can provide us with those crash reports if and when they pop up, then I think we can move forward, because reproduction efforts on this side have failed so far.

**Comment by Zanibas** [comment] 2016-11-10 01:15
I'm closing this issue for organization's sake, but please re-open if you run into this issue again!

**Closed by Zanibas** 2016-11-10 01:15 UTC
Labels: bug, cant reproduce

**Comment by Blindmikey** [comment] 2017-01-06 22:54
Just to note, I too see the whole browser crash when switching to live network.

**Comment by frankiebee** [comment] 2017-01-06 23:13
@Blindmikey if you don't, mind could you provide us with an OS name and version along with your chrome version?

**Comment by Blindmikey** [comment] 2017-01-08 02:13
MetaMask: 2.14.1
Chrome: 55.0.2883.87 m (64-bit)
Windows 10 Home v1607 Build 14393.576

**Comment by frankiebee** [comment] 2017-01-08 02:25
And you only see this when switching networkers?

**Comment by Blindmikey** [comment] 2017-01-10 18:28
Yes - I'm defaulted to the Ropsten Test Network - and when trying to switch to live, the browser crashes. When reloading the browser, I find I'm still in the test network.
