### ISSUE TITLE
Request: disable on this page

### ISSUE THREAD

**Issue by aakilfernandes** [MetaMask/metamask-plugin#980] opened 2017-01-10 18:17 UTC
Trying to use browser solidity and a friendly little fox keeps popping up =). Would be nice to be able to disable metamask on certain pages.

https://ethereum.github.io/browser-solidity/

**Comment by flyswatter** [comment] 2017-01-10 18:46
Closing as duplicate of #714.

We know this is important, and we want to get to it soon.

**Closed by flyswatter** 2017-01-10 18:46 UTC

**Comment by flyswatter** [comment] 2017-01-10 19:13
Also though, in the mean while you can right click MetaMask, select manage extensions, and uncheck metamask's "enabled" box to disable it.

- Dan
