### ISSUE TITLE
Metamask plugin is quite slow at times (ui freeze)

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-plugin#863] opened 2016-11-22 12:38 UTC
Upon clicking on the fox icon, the metamask plugin popup takes time to appear and can be frozen sometimes.

Similarly and to a greater extent the transaction popup freeze quite often. I can hear my pc's fan speeding up too. The UI is sometime non responsive.

System tested : Windows 7 chrome Version 54.0.2840.99 m

**Comment by Zanibas** [comment] 2016-11-28 23:15
Does this also happen on fresh install, or after the app has been installed for some time?

**Comment by wighawag** [comment] 2016-11-30 10:37
I just tried and it seems that on fresh install (or browser reboot) it is faster (though a bit slower to respond to the plugin icon than other plugin).
It seems it get slower as more tx popup appear

**Comment by flyswatter** [comment] 2017-01-02 20:08
Closing as duplicate of #789

**Closed by flyswatter** 2017-01-02 20:08 UTC
Labels: bug, ready
