### ISSUE TITLE
Cannot delete property 'define' of #<Window>

### ISSUE THREAD

**Issue by Manidos** [MetaMask/metamask-plugin#447] opened 2016-07-15 05:25 UTC
This error pops up in Chrome developer console from time to time. Closing the tab and opening a new window usually helps.
![err](https://cloud.githubusercontent.com/assets/16019131/16864475/bed97410-4a7e-11e6-90e5-0816d1686d32.png)

**Comment by kumavis** [comment] 2016-07-18 20:07
@Manidos that is unusual! Can you tell us your OS and chrome version?

**Comment by kumavis** [comment] 2016-07-19 00:59
Added some defensive code, but still want to know more about how @Manidos encountered this

**Comment by Manidos** [comment] 2016-07-19 07:46
@kumavis , 
OS: Windows 7, 32 bit
BROWSER: Chrome, v.51.0.2704.103 m

After updating Chrome to 51.0.2704.106 m, this error is no longer bothering me.
Thank you guys for all the amazing work you do!

**Comment by Manidos** [comment] 2016-07-22 06:24
I'm not sure if this is relevant, but the error persists and now I get slightly different output in the console 
![1](https://cloud.githubusercontent.com/assets/16019131/17048364/38d1084a-5007-11e6-9da5-22dd7cf790ad.png)

**Comment by Manidos** [comment] 2016-08-03 05:22
Here's the [link ](http://www.filedropper.com/files_4)to my website source (**package.json**, **server.js**, **index.html**....). It would be easier for you to reproduce this errror. After running the server, open **index.html** and refresh the page until you get the message. I hope it helps!

**Comment by kumavis** [comment] 2016-08-11 17:56
hmm i wonder if instead of `delete global.define` we just did `global.define = undefined` it would work without error

**Comment by flyswatter** [comment] 2016-08-11 18:53
Assigning to me since I have a windows VM running for dev.

**Comment by flyswatter** [comment] 2016-08-11 22:11
That filedropper link seems to have expired, @Manidos. Could you re-post? I'm trying to reproduce & solve now.

**Comment by Manidos** [comment] 2016-08-12 05:34
@flyswatter, the files are still there, just succesfully downloaded the archive. The description below wrongly shows the size to be 0 kb. Idk, a bug, I guess. Anyway, here's Dropbox link https://www.dropbox.com/s/0r6fyyun0bsp8yk/MetaMask.rar?dl=0

**Comment by flyswatter** [comment] 2016-08-15 23:18
Was unable to reproduce on my mac or a 64bit Windows 10, downloading a Windows 7 VM now.

**Comment by Manidos** [comment] 2016-08-16 00:11
@flyswatter, yesterday I tried to reproduce it also and couldn't get that error.

**Comment by flyswatter** [comment] 2016-08-16 03:01
I'm torn between closing and marking `cannot reproduce`. I think I'll just close it for now, please let us know if you ever have other leads on reproducing.

**Comment by Manidos** [comment] 2016-08-16 03:44
@flyswatter, I'm sorry for the confusion. The reason I'm not getting this error is because I've modified **require.js**  and completely forgotten about it. The files I've uploaded to dropbox contain unmodified version of require.js.  I've just run this old code again and the error is still there.  Ok, here's a little explanation: A couple of days ago I disabled MetaMask, because the error was killing me. Then I added web3.js file and connected to Geth at localhost. My website still threw some errors. After a little investigation I realised that the problem was that both requireJS and web3 declare variables **define** and **require** in global scope. Naming collision was the cause. I've managed to make my code to work without any errors by renaming these variables in require.js file. Then a bit later I enabled MetaMask, shut off node,  and continued to play around without any errors thinking that it's you who fixed the issue. 
Now my require.js file looks like this(used this as a [guide](http://requirejs.org/docs/faq-advanced.html)): 

```
var myGlobalDefine;
var myGlobalRequire = (function(){
	var require = {};
	myGlobalDefine = define;

//INSERTED ORIGINAL REQUIRE.JS CONTENTS HERE

	return require;
}());
```

![1](https://cloud.githubusercontent.com/assets/16019131/17687331/f347e5da-6395-11e6-9803-865c6ba68e53.png)

**Comment by flyswatter** [comment] 2016-08-16 03:49
Oooh, interesting!

Yeah, we do [some work to avoid global define collisions](https://github.com/MetaMask/metamask-plugin/blob/master/app/scripts/inpage.js#L52-L69), but apparently you've found a case that doesn't avoid it.

Reopening!

**Comment by kumavis** [comment] 2016-08-25 19:59
@Manidos made some changes, can you try this again on our latest version? I am unable to reproduce your bug locally

**Comment by Manidos** [comment] 2016-08-26 07:41
@kumavis, I've double checked everything. No errors now! Yay!!!

**Closed** 2016-08-26 17:27 UTC
Labels: bug, cant reproduce, ready

**Comment by alamKhan1807** [comment] 2019-09-13 08:03
What's the issue? and how to solve.
<img width="1438" alt="Screen Shot 2019-09-13 at 12 39 32 PM" src="https://user-images.githubusercontent.com/53565186/64846777-196ca880-d62b-11e9-8f83-915d88afdebc.png">

**Comment by danfinlay** [comment] 2019-09-16 22:41
@alamKhan1807 if you're having an issue similar to this one, please open a new issue and provide steps to reproduce the error you are encountering. The bugs this issue represented are resolved.
