### ISSUE TITLE
MetaMask not showing balance

### ISSUE THREAD

**Issue by bitcoinmeetups** [MetaMask/metamask-plugin#1319] opened 2017-04-08 14:13 UTC
MetaMask not showing balance

Hello,

Today MetaMask was not working. See screenshot.

![20170408211023](https://cloud.githubusercontent.com/assets/2834754/24829642/f72810c6-1c9f-11e7-9f88-b1a720e512ab.png)

Instead of showing the latest updated balance it just shows three dots (...)

It has been like that the whole afternoon and evening.

Advise please.

Bmeet

Chrome/Ubuntu 15.10

**Comment by flyswatter** [comment] 2017-04-08 23:30
Your screen shot is not showing the current network.  What network are you connected to?

The next steps would be to check the [UI state logs](https://github.com/MetaMask/faq/blob/master/LOGS.md#ui-state-logs-chrome), then the [background logs](https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome), specifically the network tab, checking for dropped connections.

We query balance from the current RPC provider, so if for some reason one is down, we're not able to query it.  I haven't heard about Infura being down, so I'm curious if you're connected to a custom, local provider.

**Comment by flyswatter** [comment] 2017-04-08 23:45
It sounds like Infura had some very heavy load and was basically down (they're our default provider).  Things should be working again now.

If you ever find our default providers are not loading blockchain data, the basic workaround is to run a local client and point MetaMask at it (geth, parity, eth-cpp, etc...).

**Comment by flyswatter** [comment] 2017-04-10 04:12
I believe this is a duplicate of #1317, and is fixed now.

Still a problem?

**Comment by flyswatter** [comment] 2017-04-17 18:53
Closing for now, let us know if this comes back.

**Closed** 2017-04-17 18:54 UTC
Labels: bug
