### ISSUE TITLE
Gas Limit - Small & Max limit bug

### ISSUE THREAD

**Issue by bneiluj** [MetaMask/metamask-plugin#1529] opened 2017-06-02 08:59 UTC
## Issue
Can't submit tx's

## Steps to Reproduce

1. Click on reveal phase from ens (nothing to do with ens but just to illustrate the steps)
2. Metamask pops in 
3. Accept the tx
4. ui modal bug appears and stops user from accepting transaction 

## Expected Behavior

When clicking on the accept button it should fire the tx. 

## Actual Results

<img width="343" alt="screen shot 2017-06-01 at 16 35 32" src="https://cloud.githubusercontent.com/assets/3680497/26717565/2e095934-477e-11e7-8c51-4b8227288cbb.png">
Can't submit tx because of a small and gaz limit bug. 
Bug happened on ENS reveal phase. Didn't test on other web3 page. 

The console doesn't show any error messages - except one from the start: 
`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ popup.js:26575`

but it looks like a print warning to me.

Please let me know which part of the `logState()` you want me to print out. 

Looking at the code - it looks like from `hex-as-decimal-input.js`: 
`HexAsDecimalInput.prototype.constructWarning` is a getting wrong min and max as ```message += `must be greater than or equal to  ${min} and less than or equal to ${max}.``` is printing a max value for `${min}` and a min value for `${max}`.

## Environment

MetaMask 3.7.2
Version 58.0.3029.110 (64-bit)

**Comment by flyswatter** [comment] 2017-06-02 16:08
Closing as duplicate of #1528.

**Closed by flyswatter** 2017-06-02 16:08 UTC
