### ISSUE TITLE
web3.version.getNetwork() stops working after changing network with metamask

### ISSUE THREAD

**Issue by chafey** [MetaMask/metamask-plugin#1166] opened 2017-03-04 13:16 UTC
Observed: web3.eth.getNetwork() never invokes callback after changing network via metamask
Expected: web3.eth.getNetwork() should not silently fail.  It should work properly, return error, throw exception or possibly reload the web page if needed when the network is changed via metmask.
 
Steps to reproduce:
1) Start chrome, create a new tab, open developer tools
2) in console type: 
web3.version.getNetwork(function(err,res) {console.log(err,res);});
observe the console output of undefined, "1" (for mainnet) is printed
3) Use metmask to change to testnet
4) in console type: 
web3.version.getNetwork(function(err,res) {console.log(err,res);});
observe that nothing is printed to console, no error is returned and no exception is thrown

**Comment by chafey** [comment] 2017-03-04 13:50
#873 related?

**Comment by flyswatter** [comment] 2017-03-04 15:33
I think related to #1148

**Comment by flyswatter** [comment] 2017-03-06 23:48
More related to #873.  You want a way to detect manual network changes.

**Comment by kumavis** [comment] 2017-03-06 23:48
This is actually bc metamask disconnects from the dapp when changing networks and we are not forcing the dapp to reload.

**Comment by kumavis** [comment] 2017-03-06 23:51
duplicate of https://github.com/MetaMask/metamask-plugin/issues/873

**Closed by kumavis** 2017-03-06 23:51 UTC
Labels: ready

**Comment by Fthi-S3074641** [comment] 2018-04-07 10:15
I had web3 1.0.0 beta and that was causing an error. 
Installing version 0.19.0 like this fix the issue:

    npm install --save web3@^0.19.0

And it worked for me.
