### ISSUE TITLE
problem with metamask, i forget two accounts with i have deposited ETH

### ISSUE THREAD

**Issue by giver75** [MetaMask/metamask-plugin#835] opened 2016-11-21 19:12 UTC
I had to reinstall metamask on another pc, using 12 words, but I lost two accounts where I had deposited Eth and bought Plutos. The two accounts are visible on Etherdelta but not operational because not connected to metamask. Plese help me. Thank you

the first account is :0x50c2bf0fe6d4824a44e43e02d76e2b32ea62daa1 that is visible
the other two are:
0x02D07522C0186a7c7ef0e602aDBc224dBa4417f2
0x90375be206Fdd52Bd3968a23DFC25708a73d3E67
not visible in metamask but only in etherdelta

**Comment by flyswatter** [comment] 2016-11-21 19:14
You're saying you lost access to accounts when restoring metamask with your 12 word seed, which *should* be impossible.

If you're willing to, would you post the first three accounts metamask generated for you, on your old and new metamask?

**Comment by giver75** [comment] 2016-11-21 19:19
yes no problem. the first account is :0x50c2bf0fe6d4824a44e43e02d76e2b32ea62daa1 that is visible
the other two are:
0x02D07522C0186a7c7ef0e602aDBc224dBa4417f2
0x90375be206Fdd52Bd3968a23DFC25708a73d3E67
not visible in metamask but only in etherdelta

**Comment by flyswatter** [comment] 2016-11-21 19:22
What are the second two accounts that your new metamask generates, after you click the `+` "Add Account" button?

![add-account](https://cloud.githubusercontent.com/assets/542863/20497103/bc7aa7ac-afdc-11e6-9c94-c11f9769640c.png)

**Comment by giver75** [comment] 2016-11-21 19:27
I tried, but you generate random account,

**Comment by flyswatter** [comment] 2016-11-21 19:28
The accounts we generate should not be random.  Would you post the accounts we generated instead of the ones you had before?

**Comment by giver75** [comment] 2016-11-21 19:30
0x760986614B73Be2FB2960C3987032a4559f33D25
0xb9BDc09e7f0EE25689C5865791A50392e4BaF0aD

**Comment by flyswatter** [comment] 2016-11-21 19:31
@christianlundkvist Can you imagine a situation that would cause this?

**Comment by giver75** [comment] 2016-11-21 19:32
0x760986614B73Be2FB2960C3987032a4559f33D25
0xb9BDc09e7f0EE25689C5865791A50392e4BaF0aD
morden test net

**Comment by flyswatter** [comment] 2016-11-21 19:48
Maybe you could try entering your 12-word seed phrase into another wallet that uses this recovery strategy, like [My Ether Wallet](myetherwallet.com) or [Jaxx](https://jaxx.io/).

Which accounts do those generate?

**Comment by giver75** [comment] 2016-11-21 19:51
I can try, but I'm not very experienced

**Comment by flyswatter** [comment] 2016-11-21 19:58
Those are simply two other wallet applications, you don't need previous experience to use them.

This is your best shot at recovering your other accounts without giving us your seed phrase to study.

**Comment by giver75** [comment] 2016-11-21 20:03
but the phrase to metamask?

**Comment by flyswatter** [comment] 2016-11-21 20:05
Yes, MetaMask uses type of phrase that is very standard, and it is used by many wallets.  The recovery phrase in metamask should also work in other BIP44 wallets.

**Comment by giver75** [comment] 2016-11-21 20:07
thank you I try...

**Comment by giver75** [comment] 2016-11-21 20:20
in jaxx i look the two transation were i have send ETH. What I do?

**Comment by flyswatter** [comment] 2016-11-21 20:21
Oh that's right, I think Jaxx only generates your first account from the seed phrase, so it's not useful for this use.

Sorry, try with My Ether Wallet?

**Comment by giver75** [comment] 2016-11-21 20:22
At this address i error find 404

**Comment by Zanibas** [comment] 2016-11-21 20:22
https://www.myetherwallet.com/#send-transaction

**Comment by flyswatter** [comment] 2016-11-21 20:23
Weird.

I'm thinking of giving him a copy of the dev branch and seeing if that generates the accounts correctly.

**Comment by giver75** [comment] 2016-11-21 20:31
I did not find myetherwallet.com :( i can send you the copy of transation?

**Comment by flyswatter** [comment] 2016-11-21 20:32
What transaction? I thought we were looking for a missing account or two.

**Comment by giver75** [comment] 2016-11-21 20:34
yes and in this accounts i have sent from polinex some ETH

**Comment by christianlundkvist** [comment] 2016-11-21 20:37
@giver75 Are you saying that you used MetaMask, and it generated three accounts for you, but when you restore it with the same seed words the first account is the same as before but the other two accounts are different?

**Comment by giver75** [comment] 2016-11-21 20:41
what should I do?

**Comment by flyswatter** [comment] 2016-11-21 20:41
I've built another copy of MetaMask from our `dev` branch, which refactors our account generation, so maybe it will fix the problem?

@giver75 try installing this copy of metamask locally, with your seed phrase.  Which accounts do you see with it?

[metamask-dev-giver.zip](https://github.com/MetaMask/metamask-plugin/files/604718/metamask-dev-giver.zip)

For how to install, read this post:
https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store

**Comment by flyswatter** [comment] 2016-11-21 20:42
@christianlundkvist that does seem to be what he is saying.

**Comment by flyswatter** [comment] 2016-11-21 20:42
@giver75 one more time for Christian, would you confirm that metamask is restoring different accounts than it originally generated for you?

**Comment by giver75** [comment] 2016-11-21 20:44
@christianlundkvist  yes metamask restore with only one account, and when i put on + generate other accounts

**Comment by flyswatter** [comment] 2016-11-21 20:45
It's especially strange to me that the first account would generate correctly, and then the *subsequent* accounts would generate incorrectly.

**Comment by christianlundkvist** [comment] 2016-11-21 20:49
@flyswatter It sounds a bit like the discrepancies we saw between bitcore and the other bip32 libraries, i.e. not correctly padding certain steps in the KDF causes different addresses to be generated.

**Comment by flyswatter** [comment] 2016-11-21 20:50
But metamask hasn't updated that algorithm yet, our published version is still using bitcore, which as far as I know, still hasn't merged in that fix..?  Or did it???!!

**Comment by flyswatter** [comment] 2016-11-21 20:50
Right, [they have not merged in that fix yet](https://github.com/bitpay/bitcore-lib/pull/97), so accounts generated in metamask should not have changed under any conditions yet.

**Comment by flyswatter** [comment] 2016-11-21 20:51
Is it possible they published some other change in the account generation algorithm?

@giver75 when did you generate your original accounts?

**Comment by flyswatter** [comment] 2016-11-21 20:52
Try installing [a build of MetaMask from when you first generated your accounts](https://github.com/MetaMask/metamask-plugin/releases).

**Comment by christianlundkvist** [comment] 2016-11-21 20:53
@giver75 Can you try going to 

https://lightwallet.io

and restore with your seed and check which addresses get generated?

**Comment by flyswatter** [comment] 2016-11-21 20:53
I'm signing off for ~2 hours, will be back soon.  Hopefully we gave you plenty of things to try in the meantime.

**Comment by giver75** [comment] 2016-11-21 21:01
@christianlundkvist I try but i don't find

**Comment by christianlundkvist** [comment] 2016-11-21 21:04
@giver75 What three addresses do you see when restoring with your seed words?

**Comment by giver75** [comment] 2016-11-21 21:06
@christianlundkvist other tree
![immagine 3](https://cloud.githubusercontent.com/assets/23628250/20500683/cbccf0fc-b036-11e6-9798-ca4c92c4a619.jpg)

**Comment by giver75** [comment] 2016-11-21 21:08
this is My situation:
![123](https://cloud.githubusercontent.com/assets/23628250/20500715/e922eb84-b036-11e6-8d68-67892c1359f8.jpg)
![1234](https://cloud.githubusercontent.com/assets/23628250/20500722/f1e3cda6-b036-11e6-9af5-6739b31acc69.jpg)

**Comment by christianlundkvist** [comment] 2016-11-21 21:08
@giver75 Ok, go to the toolbar in the upper left hand corner on lightwallet.io, go to "HD derivation path" and select "Bip44". Which addresses do you see then?

**Comment by christianlundkvist** [comment] 2016-11-21 21:11
@giver75 Is that from etherdelta? How are you importing those accounts?

**Comment by giver75** [comment] 2016-11-21 21:13
@christianlundkvist the account was generated by metamask. with bip44 the account are empy

**Comment by christianlundkvist** [comment] 2016-11-21 21:21
@giver75 When you use "Bip44" as hd derivation path do you not see the same accounts that are in metamask?

**Comment by christianlundkvist** [comment] 2016-11-21 21:24
@giver75 One thing you should do right now: Go to the Etherdelta website, choose your account and select "Export private key". Make sure you save the private keys for all your accounts. If you do that then at least no funds are lost.

**Comment by giver75** [comment] 2016-11-21 21:34
@christianlundkvist impossible I have this message

For account 0x02D07522C0186a7c7ef0e602aDBc224dBa4417f2, there is no private key available. You can still transact if you are connected to Ethereum and the account is unlocked.

**Comment by christianlundkvist** [comment] 2016-11-21 21:52
@giver75 In lightwallet.io when you use "Bip44" as hd derivation path do you not see the same accounts that are in metamask?

**Comment by giver75** [comment] 2016-11-21 21:57
@christianlundkvist not becouse ask me : 
Please enter your session PIN to unlock the Wallet-

I have only the 12 word of metamask and the pasw of metamask

**Comment by christianlundkvist** [comment] 2016-11-21 22:00
@giver75 When you use lightwallet.io you will enter the 12 words and select a "session PIN" of your own (you can use the meta mask password here). This is the one you need to reenter.

**Comment by giver75** [comment] 2016-11-21 22:11
@christianlundkvist   i see this

![kk](https://cloud.githubusercontent.com/assets/23628250/20502727/c4605e72-b03f-11e6-9586-325aeb607a46.png)

**Comment by christianlundkvist** [comment] 2016-11-21 22:12
@giver75 Ok, now go to the menu->Hd derivation path-> "bip44". and enter the metamask password. what do you see then?

**Comment by giver75** [comment] 2016-11-21 22:16
@christianlundkvist    
the same

**Comment by christianlundkvist** [comment] 2016-11-21 22:26
@giver75 So you click "bip44" and the derivation path (above the accounts) still says "Consensys"? Make sure you try it until it says "Bip44".

**Comment by giver75** [comment] 2016-11-21 22:32
@christianlundkvist I tried 5/6 times in a row but always remains on consensys

if you wont in private i send my pasword and try to recover my Eth that I think I loose

**Comment by christianlundkvist** [comment] 2016-11-21 22:43
If you only have about 30 ETH in there and don't mind then you can send me your seed and I can try to reproduce. You can send it to this address: i1725311@mvrht.com

**Comment by giver75** [comment] 2016-11-21 22:48
@christianlundkvist 

I send you a mail thank you

**Comment by kumavis** [comment] 2016-11-21 22:51
just to clarify, @christianlundkvist is not a developer from the metamask team, but is a trusted member of the ethereum community, ConsenSys and most importantly, built the underlying 'lightwallet' library.

Thanks for helping debug this problem chris! 😸

**Comment by kumavis** [comment] 2016-11-21 22:52
@giver75 do you have any tokens registered with these addresses?

**Comment by giver75** [comment] 2016-11-21 22:52
maybe for error I think..sorry

**Comment by christianlundkvist** [comment] 2016-11-21 23:28
When I try the 12 words in lightwallet and metamask I only get 

0x760986614B73Be2FB2960C3987032a4559f33D25
0xb9BDc09e7f0EE25689C5865791A50392e4BaF0aD

@flyswatter were you able to restore to an older version of metamask?

**Comment by flyswatter** [comment] 2016-11-21 23:37
@giver75 Did you ever create a new account from the EtherDelta menu like this?:

![screen shot 2016-11-21 at 3 34 19 pm](https://cloud.githubusercontent.com/assets/542863/20505169/00b613de-b000-11e6-8d15-6808da76da55.png)

If so, that is an EtherDelta account, it is not a MetaMask account, and it cannot be recovered with your metamask seed phrase. This is a very confusing issue, and it may be an important design consideration for @zackcoburn

**Comment by christianlundkvist** [comment] 2016-11-21 23:41
I've tried also a bunch of older versions of lightwallet and I can only generate the accounts

0x760986614B73Be2FB2960C3987032a4559f33D25
0xb9BDc09e7f0EE25689C5865791A50392e4BaF0aD

with the provided seed. So it seems very unclear where the other accounts came from.

**Comment by flyswatter** [comment] 2016-11-21 23:46
Yeah I'm pretty convinced that this is an EtherDelta UX issue, where @giver75 believed he had created a pair of MetaMask accounts, and thought they were backed up, and then lost them.

I think there's some serious discussion to be had about EtherDelta's hybrid account menu, where it intermingles injected accounts with its own local accounts, which should be critically backed up as soon as they're generated, but instead can be created and forgotten with one click.

**Comment by giver75** [comment] 2016-11-21 23:47
@flyswatter  yes I have create new account but not work. IF you look my etherdelta account I've some plutos and some order that I can't clear.

**Comment by flyswatter** [comment] 2016-11-21 23:48
If you still have access to that EtherDelta account, I would recommend Exporting its private key and backing it up ASAP.

If you lose access to that account, you may not recover it.

**Comment by giver75** [comment] 2016-11-21 23:49
@flyswatter  thanks I think success is what you are saying.

**Comment by giver75** [comment] 2016-11-22 00:01
when the account etherdelta I try to do an operation comes this warning:
You tried to send an Ethereum transaction but there was an error: Failed to sign transaction

thank you all for the support @christianlundkvist @flyswatter 
in my country it is very late to see you tomorrow

**Comment by zackcoburn** [comment] 2016-11-22 00:05
@giver75 If there is any way you can recover the original computer/browser, and the accounts were in fact created via EtherDelta's "New Account" option, you can export the private keys and retrieve the funds. How bad is the situation with the original computer? Maybe it's possible to recover.

For future users of EtherDelta's "New account" feature, I updated the popup window so it instructs the user to backup the private key.

**Comment by flyswatter** [comment] 2016-11-22 00:29
I'm closing this issue, because I think we know what happened now, and it's not a MetaMask issue.

**Comment by christianlundkvist** [comment] 2016-11-22 02:34
@flyswatter Yes, this seems like the most likely scenario.

**Comment by giver75** [comment] 2016-11-22 08:34
thank you all for the support, 
I seem to Understand What I have no hope of Recover My Eth.

**Comment by flyswatter** [comment] 2016-11-22 17:40
You have those accounts loaded in your browser, it sounds like you just forgot a PIN number.  Please open an issue with EtherDelta on exporting your account.  Maybe you can brute force your pin number.

**Comment by giver75** [comment] 2016-11-22 17:45
@flyswatter thank you

**Comment by giver75** [comment] 2016-11-23 17:03
In Etherdelta say me that Perhaps this is a MetaMask bug after all. The situation is that I have two accounts locked and I ooose my eth. Thank you of all for the support

**Comment by flyswatter** [comment] 2016-11-23 17:10
Could you link to the Etherdelta conversation that concluded this is probably a MetaMask bug, @giver75?

**Comment by giver75** [comment] 2016-11-23 17:15
@flyswatter I'm sorry but I can not understand what the problem at this point

**Comment by kumavis** [comment] 2016-11-23 18:52
@zackcoburn did you have additional discussion with @giver75 and determine that it may be a metamask bug?

**Comment by flyswatter** [comment] 2016-11-23 19:39
@giver75 A question that is very important that you have not answered:

The two accounts that you locked:
Did you create them within MetaMask, **or** from the EtherDelta `Add Account` menu item?

**Comment by flyswatter** [comment] 2016-11-23 19:39
(Thanks @zackcoburn)

**Comment by giver75** [comment] 2016-11-24 08:52
They were metamask accounts, that when they were no longer visible in metamask I added on Etherdelta them. In either account I made the buying and selling of Plutos, it is now locked.

**Comment by flyswatter** [comment] 2016-11-25 00:13
@giver75 try selecting the second account, and *then* selecting "export private key".

**Comment by giver75** [comment] 2016-11-25 09:01
@flyswatter the same of the first account

**Comment by kumavis** [comment] 2016-11-25 19:08
> They were metamask accounts, that when they were no longer visible in metamask I added on Etherdelta them.
@giver75
1) When you added them to Etherdelta, did you just add the address or did you import the private key?
2) "when they were no longer visible in metamask" did you reinstall metamask? how did they disappear from metamask?

**Comment by flyswatter** [comment] 2016-11-25 19:50
I have one outlandish theory that would explain giver's experience, but I really think it's a long shot.

### First, observations

1. EtherDelta will add any MetaMask account when the page is loaded with that metamask account selected.  Even after changing your metamask account selection, the old metamask account stays in the menu, it just can't transact, since it has no private key.
2. In our best screenshot (where we can see both metamask and etherdelta accounts), the first account is visible on both.
3. Giver insists that the later ones cannot export because they have no private key.

### Wild theory

This is the behavior that one would experience if they visited EtherDelta with one metamask vault, changed the account one time, then reinstalled metamask, created (did not restore) a new vault.

This would suggest there are maybe two MetaMask vaults installed, the original vault was not restored correctly, and the only reason it looks like "the same vault" is because the first account is the same in both.

### Problem with that theory

EtherDelta seems to always add later vaults below earlier vaults in its account list.

For this theory to hold water, giver would have had to:
1. Created the metamask vault w/ second account `0x76...`.
2. Created a second metamask vault, w/ second account `0x02D..`.
3. Restored the first vault again.
4. Gotten confused where those "second vault" accounts went.

### Conclusion

This is a pretty outrageous theory, but it's my first new theory in a day on this.

**Comment by giver75** [comment] 2016-11-25 19:54
@kumavis 

1) I add the address
2) my pc was broken. when I restart pc I reinstall metamask

**Comment by flyswatter** [comment] 2016-11-25 19:55
So @giver75 you are sure you only reinstalled metamask once?

**Comment by giver75** [comment] 2016-11-25 20:04
not i try many times when not working on the account...

**Comment by flyswatter** [comment] 2016-11-25 20:06
Oh, so my theory may hold water.

@giver75 is it possible that *one of the times* you reinstalled, instead of entering your old seed phrase, you just created another vault?

Is it possible you wrote down the different seed phrase for that vault?

Is it possible that this is the vault you ended up sending ether to?

**Comment by giver75** [comment] 2016-11-25 20:09
@flyswatter the phrase is correct because I had noted on the phone with a picture.

**Comment by flyswatter** [comment] 2016-11-25 20:10
Please answer: it possible that *one of the times* you reinstalled, instead of entering your old seed phrase, you accidentally created another vault?

**Comment by giver75** [comment] 2016-11-25 20:22
Not I restore the account with the old phrse. A question, if one sends ETH, to an account etherdelta without having the private key, can not use them even if you display them?

**Comment by flyswatter** [comment] 2016-11-25 20:23
That does seem to be the case.  I think EtherDelta should consider not listing accounts that are not actually available.

**Comment by giver75** [comment] 2016-11-30 12:55
I have Another. The main transfer I paid into the account that still seeing on metamask. Then I passed them on to another account that I have not the key. If they move on metamask other currencies are lost? thank you

**Closed** 2017-01-02 19:39 UTC
Labels: bug, cant reproduce

**Comment by TheKeyMaster69** [comment] 2017-12-29 03:26
Guys I have the same issue as everyone else. Ended up erasing the extension plugin and then realized I had misplaced the Wallet Seed. I have the Etherium address, the account name and the password. Would anyone be able to help me out!

Thank you in advance

**Comment by TheKeyMaster69** [comment] 2017-12-29 03:55
I am on a Mac 10.10.5 BTW

Thanks

**Comment by ifeoluwak** [comment] 2018-01-30 04:14
Hi, please am also having the same issue. I formatted my system. Then I tried to restore my vault using the seed phrasee. But all my accounts were gone!! Please help

**Comment by Fortunatus1989** [comment] 2018-02-05 11:37
Good time of day, it turned out that it was crooked windows and I lost the keywords from my wallet, there is a purse number and a password I remember. Is it possible to restore access to the wallet?

**Comment by danfinlay** [comment] 2018-02-06 07:37
You can email us for support at support@metamask.io

**Comment by Sheikhupuri** [comment] 2020-10-02 23:41
I faced same issue and I finally resolve this issue successfully 
You can recover those accounts only if you have private keys of those accounts
Just Load your private key and your account will be active 

Check this for more details : https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key

**Comment by 225kun225** [comment] 2021-12-11 05:57
I have the same problem, after reinstalling MM, i can't find my new account, i still have the wallet address. ANYONE help!!!

**Comment by johnjames333** [comment] 2021-12-21 13:33
@225kun225 @giver75 @TheKeyMaster69 @Fortunatus1989 
we have developed our own hardware for cracking Metamask wallet password with superfast speed. we can find and recover any lost address or balance from new or previous metamask if you install new app or extension.
and if you still has problem I can help you run it. you can find my contact details on my profile
or you can send me message in telegram: @johnjames333

**Comment by richardsonn09** [comment] 2022-01-30 21:30
@225kun225 
If you couldn't restore your lost fund, I can recover your wallet if you want need help send me email : anywalletrecovery@gmail.com

**Comment by DanielsBerlin** [comment] 2023-01-21 14:29
@225kun225 
you can use hashcat to crack your password.
