### ISSUE TITLE
Client side log filters fails

### ISSUE THREAD

**Issue by Tectract** [MetaMask/metamask-plugin#1485] opened 2017-05-24 05:35 UTC
Metamask is no longer working at all for me. 

All I get is:

"_blockTracker wait for first block"

It's unresponsive. Page that was working seemingly fine two weeks ago is not working now... odd.

See issue here:
https://github.com/MetaMask/provider-engine/issues/149

**Comment by kumavis** [comment] 2017-05-24 05:39
@Tectract hello can you give reproduction instructions for www.enledger.io/ethdeployer

what can i do to test. what should i expect to happen.

**Comment by Tectract** [comment] 2017-05-24 05:48
You should be able to connect to mainnet via metamask, and compile/deploy ethereum contracts from that page. It simple parses the contract you paste in the box and tries to compile / deploy it. Open the web console to see the output there, that's where the error get's printed by javascript.

The relevant source is here: 

https://github.com/Tectract/EthDeployer/blob/master/src/Deploy.js

**Comment by Tectract** [comment] 2017-05-24 05:49
I succesfully used this tool with no issues, just two weeks ago. Source code on my end hasn't changed...

**Comment by Tectract** [comment] 2017-05-24 05:49
You can also test the EthDeployer against a localhost node, with or without metamask running...

**Comment by kumavis** [comment] 2017-05-24 05:50
> I succesfully used this tool with no issues, just two weeks ago. Source code on my end hasn't changed...

yes we published a change today that seems to have broken something

**Comment by kumavis** [comment] 2017-05-24 05:51
@Tectract ok please give me some sample data
i should be able to drop it into the textbox and press "compile & deploy" to trigger metamask tx window?

**Comment by Tectract** [comment] 2017-05-24 05:59
You can use the solidity smart-contract here for testing:
https://github.com/Tectract/ethereum-demo-tools/blob/master/GeektSolidity/contracts/Geekt.sol

Yep, you just paste it in and click the button. Here's a screencap:

![deployer_deployed](https://cloud.githubusercontent.com/assets/3859005/26388811/cfae4244-4013-11e7-86f9-7d75a4d349e3.jpg)

**Comment by Tectract** [comment] 2017-05-24 06:00
I was just going back to do new screencaps, but surprisingly, it no longer works!

**Comment by Tectract** [comment] 2017-05-24 06:01
This is for an article for Blockgeeks ;)

**Comment by kumavis** [comment] 2017-05-24 06:02
yeah actual error i the network tab on mainnet is
```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32050,
    "message": "Error while compiling code.",
    "data": "Error { repr: Os { code: 12, message: \"Cannot allocate memory\" } }"
  },
  "id": 5859018694634867
}
```

reported to infura

**Comment by kumavis** [comment] 2017-05-24 06:02
@tectract if you point metamask to a local node, does it work?

**Comment by Tectract** [comment] 2017-05-24 06:03
Nope. Same error.

**Comment by kumavis** [comment] 2017-05-24 06:04
@Tectract what node are you running?

**Comment by kumavis** [comment] 2017-05-24 06:05
> Nope. Same error.
can you look in the background network tab https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

and report the error

**Comment by Tectract** [comment] 2017-05-24 06:22
Ok, here you go. I'm just running testRPC.

background.js:4035 Error in RPC response:
 Object {message: "Error: Couldn't find block by reference: 0x1↵    a…node_modules/web3-provider-engine/index.js:95:18)", code: -32000}code: -32000message: "Error: Couldn't find block by reference: 0x1↵    at BlockchainDouble.getBlock (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/lib/blockchain_double.js:124:21)↵    at GethApiDouble.eth_getBlockByNumber (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:119:25)↵    at GethApiDouble.handleRequest (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/lib/subproviders/geth_api_double.js:61:10)↵    at next (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)↵    at SolcSubprovider.handleRequest (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/solc.js:28:7)↵    at next (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)↵    at VmSubprovider.handleRequest (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:42:12)↵    at next (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)↵    at GethDefaults.handleRequest (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/lib/subproviders/gethdefaults.js:17:12)↵    at next (/home/locutus/.nvm/versions/node/v6.2.2/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:95:18)"__proto__: Objectlogger @ background.js:4035onPayloadHandled @ background.js:66018(anonymous function) @ background.js:57580(anonymous function) @ background.js:8685replenish @ background.js:8565iterateeCallback @ background.js:8555(anonymous function) @ background.js:8701resultObj.id @ background.js:57562(anonymous function) @ background.js:8776replenish @ background.js:8570iterateeCallback @ background.js:8555(anonymous function) @ background.js:8701resultObj.id @ background.js:57562(anonymous function) @ background.js:8776replenish @ background.js:8570iterateeCallback @ background.js:8555(anonymous function) @ background.js:8701resultObj.id @ background.js:57562(anonymous function) @ background.js:8776replenish @ background.js:8570iterateeCallback @ background.js:8555(anonymous function) @ background.js:8701resultObj.id @ background.js:57562(anonymous function) @ background.js:8776replenish @ background.js:8570iterateeCallback @ background.js:8555(anonymous function) @ background.js:8701(anonymous function) @ background.js:64248resultObj.id @ background.js:57560(anonymous function) @ background.js:8776replenish @ background.js:8570iterateeCallback @ background.js:8555(anonymous function) @ background.js:8701resultObj.id @ background.js:57562(anonymous function) @ background.js:8776replenish @ background.js:8570iterateeCallback @ background.js:8555(anonymous function) @ background.js:8701resultObj.id @ background.js:57562(anonymous function) @ background.js:8776replenish @ background.js:8570(anonymous function) @ background.js:8574eachLimit @ background.js:8442(anonymous function) @ background.js:8502end @ background.js:57557

**Comment by flyswatter** [comment] 2017-05-24 06:24
That's actually an old testrpc error. You should update `npm install -g ethereumjs-testrpc`.

**Comment by Tectract** [comment] 2017-05-24 07:28
Testrpc updated, thanks, now on 3.0.5. Loading this page with metamask connected to localhost:8545 testrpc node yields no error messages in the background network console.

However, web3.eth.accounts object is not being populated. Here's the output I see in my console:

MetaMask - injected web3
saw injected web3!
saw eth accounts: 
[]
_blockTracker wait for first block
available compilers: solidity
saw netId:20
This is an unknown/localhost network: localhost

So, interestingly, it does see the compiler solidity as available in the web3 object, but accounts didn't make it through. I'm wondering if there's some race on web3 "new". 

If I just disable metamask, it connect to testrpc localhost, sees accounts, compiles / deploys locally no problem. Craziest thing is that I didn't change my code since two weeks ago when I developed this code while testing it extensively, and didn't see ANY of these issues! Not sure what changed.

I could use some advice trying to figure out if there's really a solc issue on the webserver, but I'm skeptical that's the problem, it seems to have plenty of available memory.

**Comment by Tectract** [comment] 2017-05-24 08:05
Compilation of the contract from the command line on the web-server using solc succeeds, no memory allocation issue there. It WAS spitting out nice solc error messages if you had like a typo in your contract. Doesn't seem to actually be attempting to hit the server anymore when you hit the "compile/deploy" button, it's getting stuck somewhere in Metamask. Web-server is not showing any activity on the button press as you would expect... Still trying to figure out what's going on here...

**Comment by Tectract** [comment] 2017-05-24 08:06
Interestingly, if you reload the page a BUNCH of times, it will load the accounts, like once in 20 tries. That's why I'm considering there may be a race issue somewhere...

**Comment by Tectract** [comment] 2017-05-24 08:09
It's relatively simple to actually test the EthDeployer locally, or to deploy it on your own web-server for testing...

I have pretty detailed notes on the setup I did, in the readme here:

https://github.com/Tectract/EthDeployer

It's just a simple create-react-app.

**Comment by Tectract** [comment] 2017-05-24 08:15
If I load up the page, then type:
web3.eth.accounts 

into the console, it DOES show that it has loaded the account. Definite race issue in my instantiation... Hmmmmm....

**Comment by Tectract** [comment] 2017-05-24 16:24
I believe this issue has been mislabeled. The issue is not that the LOG is failing, it's that metamask is no longer working for me, and appears to be hanging on this message:

"_blockTracker wait for first block"

I'm still unable to use metamask. I would greatly appreciate more help troubleshooting here.

**Comment by kumavis** [comment] 2017-05-24 16:25
> "_blockTracker wait for first block"
is just a comment - it will be removed soon. what else do you expect to happen after that message?

**Comment by kumavis** [comment] 2017-05-24 16:32
so worth noting that we dont support the `eth_compileSolidity` method, which your system relies on

**Comment by kumavis** [comment] 2017-05-24 16:32
I would expect it to work against testrpc

**Comment by kumavis** [comment] 2017-05-24 16:42
seems to be working against testrpc 👍 

tho requries the solidity version pragma statement

**Comment by kumavis** [comment] 2017-05-24 16:43
Closing for now, let me know if you think the issue was not covered there

**Closed** 2017-05-24 16:44 UTC

**Comment by Tectract** [comment] 2017-05-24 17:01
I expect the contract to compile and deploy succesfully when you click the "compile and deploy" button on the EthDeployer. Nothing happens, I just get a "compile error" returned from metamask and the webserver doesn't even get hit, at all.

Here is my instantiation routine that I'm looking at now:

```
function loadWeb3() {
  let web3Injected = window.web3;
  if(typeof web3Injected !== 'undefined'){
    console.log("saw injected web3!");
    web3 = new Web3(web3Injected.currentProvider);
  } else {
    console.log("did not see web3 injected!");
    web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
  }
}

  getInfo(){
    var outerThis = this;
    if(typeof web3.eth !== 'undefined'){
      console.log("saw eth accounts: ");
      console.debug(web3.eth.accounts);
...

```

So I'm calling:
```
 loadWeb3() ;
 getInfo();
```

And I believe there is some type of race condition here, because the web3.eth.accounts object is never populated when getInfo() is run. So I'm debugging that race issue.
 
I'm debugging this race issue, but it actually seems to be working much better this morning, oddly.

I'm debugging solc on my web-server, trying to verify that it is actually being run. Any useful suggestions are welcome for how to do that...

As you can see this tool WAS working just fine about two weeks ago, from the screenshot I provided. I think metamask does support compilation...
