### ISSUE TITLE
Error: PortDuplexStream - disconnected

### ISSUE THREAD

**Issue by kulik77** [MetaMask/metamask-plugin#1084] opened 2017-02-03 08:52 UTC
Error: PortDuplexStream - disconnected
    at PortDuplexStream._write (contentscript.js:265)
    at doWrite (contentscript.js:4988)
    at writeOrBuffer (contentscript.js:4977)
    at PortDuplexStream.Writable.write (contentscript.js:4915)
    at PostMessageStream.ondata (contentscript.js:4060)
    at PostMessageStream.EventEmitter.emit (contentscript.js:2687)
    at readableAddChunk (contentscript.js:3731)
    at PostMessageStream.Readable.push (contentscript.js:3690)
    at PostMessageStream._onMessage (contentscript.js:3339)

Getting this error after change network and call web3.version.getNetwork
MetaMask version 3.1.2

**Comment by flyswatter** [comment] 2017-02-03 08:52
For now, you need to manually reload a page after changing the metamask network.

**Comment by kulik77** [comment] 2017-02-03 09:06
How can I do it? There is a network change event?

**Comment by flyswatter** [comment] 2017-02-03 09:22
No, manually.  You have to just click the reload button in your browser.

We are already planning to auto-reload pages that have used web3 to close #873, in the meanwhile you have to reload pages manually.

Closing as a duplicate of that issue.

**Closed by flyswatter** 2017-02-03 09:22 UTC
