### ISSUE TITLE
Metamask submits duplicate transactions to TestRPC if clicking "accept" twice quickly

### ISSUE THREAD

**Issue by IAMtheIAM** [MetaMask/metamask-plugin#1676] opened 2017-06-26 21:57 UTC
When submitting a transaction on TestRPC through MetaMask for the amount of 1 eth, the metamask prompt appears. However if I click "accept" really fast twice before the prompt disappears, it will submit two transactions to the TestRPC blockchain, and it will indeed withdrawn 2 eth from the sending wallet and deposit 2 eth in the receiving wallet.

Prompt for 1 eth to be sent -  clicking "accept" twice quickly - **Initial balance 985.972**
![1eth_2017-06-26_1453](https://user-images.githubusercontent.com/13709948/27562042-86f9db7c-5a7f-11e7-837f-d1f9fe4e3d8e.png)

blockchain records 2 transactions - 2 seconds apart
![2_transactions_2017-06-26_1454](https://user-images.githubusercontent.com/13709948/27562043-86fb8580-5a7f-11e7-9f0b-a0816028917d.png)

metamask only shows 1 eth was sent. But 2 was sent when wallet balance is checked. **Final balance 983.972**
![1_eth_sent_2017-06-26_1454](https://user-images.githubusercontent.com/13709948/27562041-86f8509a-5a7f-11e7-9c52-8c91a4c83b90.png)

If I click accept SUPER fast I can get it to submit 3 transactions to TestRPC blockchain.

This seems like a big bug. Can anyone reproduce?

**Comment by tmashuang** [comment] 2017-06-26 23:27
Fixed in #1677.

**Closed by tmashuang** 2017-06-26 23:27 UTC
Labels: bug, L3-userinterface, P0-stopdroproll

**Comment by eGBP** [comment] 2019-06-29 11:13
Today it happened with me on main network. I sent 0.15 ETH but i think i clicked twice on submit and it sent duplicate transaction. Glad it was my own address otherwise would have been cost me 0.15 ETH. It is very big bug

**Comment by bdresser** [comment] 2019-07-01 18:06
@eGBP we're unable to reproduce this bug. Do you encounter it reliably? Could you provide more detailed steps on exactly what you did, or include a video to help us reproduce?
