### ISSUE TITLE
Deprecated KeyStore constructor

### ISSUE THREAD

**Issue by Zanibas** [MetaMask/metamask-plugin#637] opened 2016-09-09 21:52 UTC
From our tests:

```
  IdentityStore
    #createNewVault
{ Error: connect ECONNREFUSED 13.92.235.44:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '13.92.235.44',
  port: 443 }
The new KeyStore constructor has been deprecated in favor of KeyStore.createVault(), and will be removed in a future version. Read issue #109 for info. https://github.com/ConsenSys/eth-lightwallet/issues/109
saved to keystore
      #recoverFromSeed
The new KeyStore constructor has been deprecated in favor of KeyStore.createVault(), and will be removed in a future version. Read issue #109 for info. https://github.com/ConsenSys/eth-lightwallet/issues/109
        ✓ should return the expected keystore (240ms)
    #recoverFromSeed BIP44 compliance
The new KeyStore constructor has been deprecated in favor of KeyStore.createVault(), and will be removed in a future version. Read issue #109 for info. https://github.com/ConsenSys/eth-lightwallet/issues/109
  ```

**Comment by flyswatter** [comment] 2016-09-09 21:57
Duplicate of #555.

I added that deprecation warning to light wallet, we still need to move over to the new method now that they've published.

**Closed by flyswatter** 2016-09-09 21:57 UTC
Labels: bug
