### ISSUE TITLE
Show transaction pending vs confirmed

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-plugin#874] opened 2016-11-22 21:21 UTC
how is this not already a thing?

**Comment by kumavis** [comment] 2016-11-22 21:22
> The History of TXs shown in MetaMask could be more clear about which TXs are pending and which actually reached the blockchain already. And if pending, being able to visualize the signed TX so that I can manually broadcast it would be great.

**Comment by flyswatter** [comment] 2017-01-02 20:09
Closing as duplicate of #901

**Closed** 2017-01-02 20:09 UTC
Labels: enhancement, UI
