### ISSUE TITLE
TypeError thrown while calling 'web3.currentProvider.sendAsync' when metamask is locked

### ISSUE THREAD

**Issue by qjflores** [MetaMask/metamask-plugin#1612] opened 2017-06-15 06:21 UTC
A TypeError is thrown while calling 'web3.currentProvider.sendAsync' when metamask is locked

```
web3.currentProvider.sendAsync({jsonrpc: "2.0", id: 1, method: 'personal_sign', params: [web3.eth.accounts[0], data] },
  function(err, result) {
    console.log(err) // this is null - weird
    console.log(result) // {id: 1, jsonrpc: "2.0", error: Object}
    console.log(result.error.code) // -32000
    console.log(result.error.message) // TypeError: Cannot use 'in' operator to search for 'from' in null
    })
```

the full traceback
```
TypeError: Cannot use 'in' operator to search for 'from' in null
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:66453:19
    at Array.reduce (native)
    at cloneTxParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:66452:31)
    at SanitizerSubprovider.handleRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:66429:21)
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:58272:18)
    at NonceTrackerSubprovider.handleRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:66332:7)
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:58272:18)
    at DefaultFixtures.FixtureProvider.handleRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:65762:5)
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:58272:18)
    at Proxy.Web3ProviderEngine._handleAsync (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:58259:3)
```

**Comment by tmashuang** [comment] 2017-06-15 06:33
I think to provide the account address while Metamask is locked would be a security hazard.

**Comment by qjflores** [comment] 2017-06-15 07:25
was surprised to see `err` as null. 

```
web3.currentProvider.sendAsync({jsonrpc: "2.0", id: 1, method: 'personal_sign', params: [web3.eth.accounts[0], data] },
  function(err, result) {
    if(!err){
        var signature = result.result
        // do some cool passwordless stuff
    } else {
        // prompt the user to unlock their metamask account and try again
    }
}) 
```

**Comment by flyswatter** [comment] 2017-06-15 16:34
Yes, you need to make sure the user is signed in first, but we should detect this and throw a better error for it, so I'm keeping it open.

**Comment by Zanibas** [comment] 2017-06-19 18:04
Duplicate of #1575

**Closed** 2017-06-19 18:04 UTC
Labels: L0-provider, P3-soon, T0-bug
