### ISSUE TITLE
on MetaMask update tab continuously reloads

### ISSUE THREAD

**Issue by ropod7** [MetaMask/metamask-plugin#931] opened 2016-12-17 13:16 UTC
Hello,
I see that you've handled exception on jump between networks. Good job!

But now if you are going away from Dapp browser tab this tab always reloads. If there running any Js widget with any user values it will be reloaded again and values redefined.

You may see reloads on solidity-browser.

**Comment by ropod7** [comment] 2016-12-17 15:34
MetaMask Version 2.14.0

**Comment by ropod7** [comment] 2016-12-17 19:19
And there is a video: https://www.youtube.com/watch?v=tGrf8-RiA6w
Same issue on Ubuntu and windows.

**Comment by flyswatter** [comment] 2016-12-17 20:33
Closing as a duplicate of #746.  We're actually aware of this bug, but probably want @kumavis to do it, b/c he's the one who understands the issue.  I'll try to get him on it sooner.

**Closed** 2016-12-17 20:35 UTC
