### ISSUE TITLE
Display function names and parameters for contract calls via method registry.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-plugin#1465] opened 2017-05-20 20:25 UTC
Parity launched a method registry dApp a while back that allows contract authors to publish the ABI of their contracts to Ethereum so that signers (e.g., MetaMask, Parity, etc.) can display to the user the name of the function being signed and the parameters being passed rather than just telling the user "you are signing a thing!".

In order to provide users with more confidence that the dApp they are calling is doing something reasonable/expected, it would be nice if MetaMask supported using this registry to display contract information.

The registry can be found here: https://github.com/paritytech/contracts/blob/master/SignatureReg.sol As far as I know, the UI for the dApp is only available in Parity, but presumably it could be hosted elsewhere fairly easily.

This is what the Parity UI looks like when using the register metadata:
![image](https://cloud.githubusercontent.com/assets/886059/26279112/c54a60aa-3d5f-11e7-8c1f-af779492cc3b.png)

**Comment by flyswatter** [comment] 2017-05-20 20:54
Duplicate of #1142, although the Parity registry isn't mentioned there yet, so I'll re-post this on that issue.

**Closed by flyswatter** 2017-05-20 20:54 UTC
