### ISSUE TITLE
Imported accounts via JSON vanish after restarting Chrome

### ISSUE THREAD

**Issue by madvas** [MetaMask/metamask-plugin#1134] opened 2017-02-20 11:55 UTC
Steps to reproduce:
- Import account -> JSON file
- Type password
- Everything works fine
- Restart Chrome
- Switch accounts
- Imported account is not there anymore

**Comment by Zanibas** [comment] 2017-02-20 18:40
Possibly resolved by #1123, will close after verified in production.

**Comment by Zanibas** [comment] 2017-02-21 00:04
Verified--seems to be fixed!

**Comment by madvas** [comment] 2017-02-21 08:28
This is **not** fixed as of `Version 3.3.0: Pickled Plecostomus`

**Comment by flyswatter** [comment] 2017-02-21 16:55
That's very interesting, I think you're having a different problem than we originally suspected.

My new guess is that for some reason your computer is having trouble persisting your new account to disk. To check this theory, I'll need you to open up MetaMask's background console and look for any red error messages while you import your account.

We have a guide on collecting these logs here:
https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome

**Comment by madvas** [comment] 2017-02-21 18:28
So found in logs following: 
```
Attempt to import as EtherWallet format failed, trying V3...
```
It was logged after I clicked in Import on JSON, but it still got account imported tho. For accounts to be vanished I don't really have to restart Chrome, just changing network is enough.

![image](https://cloud.githubusercontent.com/assets/3857155/23178711/c434876a-f86b-11e6-84d8-6c26d8fcf6d1.png)

**Comment by madvas** [comment] 2017-02-21 18:31
When I open new tab with random page I get following error, not sure if relevant
![image](https://cloud.githubusercontent.com/assets/3857155/23178887/56728f96-f86c-11e6-9f6a-4056f1f6eb5d.png)

**Comment by flyswatter** [comment] 2017-03-06 20:24
Sorry @madvas, none of those logs are the culprit.  We'd need more information about the file that is failing to import.

You can contact me on our slack, we can maybe look closer at this?  Most people aren't having this problem.

**Comment by madvas** [comment] 2017-03-12 21:04
I'm importing json directly from `~/Library/Ethereum/keystore/` on Mac OS
Those accounts were created by Mist

It says "Loose" when I import such account:
![image](https://cloud.githubusercontent.com/assets/3857155/23835891/7a3777c2-076f-11e7-9ba8-c3144bb21d79.png)

**Comment by flyswatter** [comment] 2017-03-12 22:02
We'll try to investigate a bit more this week.

**Comment by flyswatter** [comment] 2017-04-26 22:29
Sorry for the long wait @madvas.

The "lose" tag is nothing to worry about:
https://github.com/MetaMask/faq/blob/master/USERS.md#loose-accounts

Is the loose label the only issue? Are you actually losing these accounts after restarting the browser? We haven't been able to reproduce, so I'm going to close for now, but will reopen if there are any other specific details that might help us reproduce.

**Closed by flyswatter** 2017-04-26 22:29 UTC
Labels: blocked, bug

**Comment by madvas** [comment] 2017-04-27 04:08
This issue seems to be resolved now for me. Thank you
