### ISSUE TITLE
Is it possible to use hybrid provider?

### ISSUE THREAD

**Issue by marathonfail** [MetaMask/metamask-plugin#1316] opened 2017-04-08 09:48 UTC
I want all the READ calls to go to my server and only the sendTransaction call to go to MetaMask. Also, does MetaMask only cache blocks upto a certain level? Because for earlier blocks, MetaMask did not return values and causing my app to not function properly.

I also made certain changes to my app to have readWeb3(pointing to my server) and writeWeb3(pointing to metamask). But this doesn't seem to be working well. 

Please take a look at: http://ethwordchain.com

Here is the commit diff for such a setup. https://github.com/marathonfail/marathonfail.github.io/commit/6de082ad0252a741375fc61461e8d341ec6fe1de#diff-fd41383df4389ed6ee75f68becb796d1

Let me know if it is ok to use MetaMask for all READ calls also. Which may be many depending on the working of the app.

**Comment by marathonfail** [comment] 2017-04-08 11:01
I further dug into this.

I'm getting this exception when trying to make a call to the contract using the metamask provider.

It comes from inpage.js at the specified lines. Let me know how it is possible to debug what is causing this error.

Error: Internal error
    at Object.InvalidResponse (bundle.js:33702)
    at bundle.js:36819
    at inpage.js:179
    at inpage.js:6682

Usually, MetaMask extension opens when I call a method on contract, but now after 5-10 seconds, I get this error message without the extension being opened. Not sure what is the cause. Let me know if you have further insights into this.

Thanks!

**Comment by flyswatter** [comment] 2017-04-10 18:23
Hi there!

1. It's definitely possible to do reads from one provider and writes to another, that's an interesting use case.
2. If I were doing this, I would do it with `web3-provider-engine`, and create a `read-subprovider` right before the `rpc-subprovider`, to forward read methods to one endpoint, and write methods to another.
3. That said, you can just read from metamask's provider. We understand this may be a lot, but it also may represent a user pointing MetaMask at a local blockchain, so it could actually scale better than even providing your own instance.
4. An `InvalidResponse` error looks like a problem. I would check [the background logs](https://github.com/MetaMask/faq/blob/master/LOGS.md#background-logs-chrome), go to the `network` tab, and look for a red request, and try to find what request returned an invalid response.  If you can isolate it, and tell us what it is, we might be able to reproduce the problem and fix it.

**Comment by marathonfail** [comment] 2017-04-12 03:16
Hi! Thanks for your response.

I think MetaMask had troubles when I posted this issue. The InvalidResponse/unable to use two providers(for READ/WRITE) was a problem at that time. I no longer got the same issue once MetaMask was back to normal. So I think we can close this issue as such.

I will take a look at how to implement read-subprovider in the way you suggested.

For #3 - If you think that there is no problem using MetaMask for all reads, we will continue using it. I just want to make sure that it is a scalable approach and the requests are not eating up someone else's resources :) I agree with your point- the user could point to a local blockchain. Do you also know how many people point to localhost when using MetaMask? Just wanted to understand the behavior here.

Thanks!

**Comment by flyswatter** [comment] 2017-04-12 13:25
We don't have any way to know how many users are pointing at local providers, but our backend (Infura) is committed to supporting our requests for now, and we're also working towards peer-gossip strategies that will allow us to scale going forwards, so part of our goal is to let you not worry about the user's provider.

**Closed by flyswatter** 2017-04-12 13:25 UTC
