### ISSUE TITLE
JSON RPC ERROR from sending a transaction

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#1160] opened 2017-03-01 20:50 UTC
You can reproduce by sending ether to the test faucet. How ever it does not seem like their are logs showing up for it in the background page and the tx still goes through.
```
Error: Invalid JSON RPC response: {"id":5,"jsonrpc":"2.0"} at Object.InvalidResponse (chrome-extension://kkkkpgbahdiooeldpgejhhlhlhjlbcib/scripts/inpage.js:6705:27885) at chrome-extension://kkkkpgbahdiooeldpgejhhlhlhjlbcib/scripts/inpage.js:6706:26989 at chrome-extension://kkkkpgbahdiooeldpgejhhlhlhjlbcib/scripts/inpage.js:179:7 at chrome-extension://kkkkpgbahdiooeldpgejhhlhlhjlbcib/scripts/inpage.js:6682:5
```

**Comment by flyswatter** [comment] 2017-03-06 19:11
Duplicate of #1168

**Closed by flyswatter** 2017-03-06 19:11 UTC
Labels: bug
