### ISSUE TITLE
*Contract Published* when it's not

### ISSUE THREAD

**Issue by Manidos** [MetaMask/metamask-plugin#483] opened 2016-07-26 15:09 UTC
OS: Windows 7, 32 bit
BROWSER: Chrome, v.51.0.2704.103 m

![1](https://cloud.githubusercontent.com/assets/16019131/17143330/dab0c4fa-5374-11e6-913a-f1fc6ed3c2e5.png)
![2](https://cloud.githubusercontent.com/assets/16019131/17143331/dab19b3c-5374-11e6-9fe2-05eca1adef78.png)
![3](https://cloud.githubusercontent.com/assets/16019131/17143332/dab3cdf8-5374-11e6-96c2-87e372f09666.png)
![4](https://cloud.githubusercontent.com/assets/16019131/17143333/daba7b44-5374-11e6-86aa-5b8b7f551f5c.png)

**Comment by flyswatter** [comment] 2016-07-26 15:19
Thanks for the report!

This is a duplicate of #226, you can follow its progress there.

**Closed by flyswatter** 2016-07-26 15:19 UTC
