### ISSUE TITLE
some transactions not sending enough gas

### ISSUE THREAD

**Issue by frankiebee** [MetaMask/metamask-plugin#691] opened 2016-10-03 23:39 UTC
"Hey Metamask! I was trying to send a transaction to claim the prize [here](http://challenges.glasshunt.co/challenges/9) and it was not sending enough gas with my transaction which resulted in an execution error on the blockchain. Ended up having to use myetherwallet. Would be great if there was a little advanced option to determine the amount of gas you want to provide"

^^^ this was a comment found on reddit dropping it in an issue so we don't loose track of it

**Comment by flyswatter** [comment] 2016-10-03 23:41
Duplicate of #495.

This would be a crazy easy feature to add, and would have a huge user benefit. Feel free to grab this as a top priority, @frankiebee.

I'm going to close this as a duplicate, though.  Grab the other issue.

**Closed by flyswatter** 2016-10-03 23:41 UTC

**Comment by frankiebee** [comment] 2016-10-03 23:43
Oh sweet yeah i'll get on that then.
